showWelcomeMessage = False
experiment = 'PROJECTIONS'
targetVars = ['pr']
methods = {'pr': ['RAW', 'ANA-SYN-1NN', 'GLM-LIN']}
calibration_years = (2000, 2006)
single_split_testing_years = (2000, 2003)
split_mode = 'single_split'
reference_years = (2000, 2004)
reanalysisName = 'ERA5'
grid_res = 1.0
saf_lat_up = 46.0
saf_lon_left = -15.0
saf_lon_right = 9.0
saf_lat_down = 34
reaNames = {'tasmax': 'mx2t', 'tasmin': 'mn2t', 'tas': 't2m', 'pr': 'tp', 'uas': 'u10', 'vas': 'v10', 'sfcWind': 'ws', 'hurs': '-', 'clt': 'tcc', 'tdps': 'd2m', 'ps': 'sp', 'huss': '-', 'ua': 'u', 'va': 'v', 'ta': 't', 'zg': 'z', 'hus': 'q', 'hur': 'r', 'td': '-', 'psl': 'msl', 'rsds': 'issrd', 'rlds': 'istrd', 'evspsbl': 'e', 'evspsblpot': '-', 'mrro': 'ro', 'mrso': 'swvl1'}
modNames = {'tasmax': 'tasmax', 'tasmin': 'tasmin', 'tas': 'tas', 'pr': 'pr', 'uas': 'uas', 'vas': 'vas', 'sfcWind': 'sfcWind', 'hurs': 'hurs', 'clt': 'clt', 'tdps': 'tdps', 'ps': 'ps', 'huss': 'huss', 'ua': 'ua', 'va': 'va', 'ta': 'ta', 'zg': 'zg', 'hus': 'hus', 'hur': 'hur', 'td': '-', 'psl': 'psl', 'rsds': 'rsds', 'rlds': 'rlds', 'evspsbl': 'evspsbl', 'evspsblpot': 'evspsblpot', 'mrro': 'mrro', 'mrso': 'mrso'}
preds_targetVars_dict = {'pr': ['pr']}
saf_list = ['pr']
scene_names_list = ['HISTORICAL']
model_names_list = ['SF2000-2023m7_ens0']
climdex_names = {'pr': ['Pm', 'PRCPTOT', 'R01', 'SDII', 'R95p']}
inverse_seasonNames = ['ANNUAL', 'DJF', 'DJF', 'MAM', 'MAM', 'MAM', 'JJA', 'JJA', 'JJA', 'SON', 'SON', 'SON', 'DJF']
apply_bc = True
apply_bc_bySeason = True
bc_method = 'PSDM'
myTargetVarName = ''
myTargetVarMinAllowed = None
myTargetVarMaxAllowed = None
myTargetVarUnits = ''
myTargetVarIsAdditive = False
